class <%= class_name %>

  #This class was generated by Monglobal
  #You should think twice before you edit this file

  include MongoMapper::Document
  include Monglobal::Translates

  <% newklass.keys.each do |key, val| %><% if val.name != "_id" %>
  <%= "key :#{val.name}, #{val.type}" %><% if val.default_value %>, :default => <%= val.default_value %><% end %><% end %><% end %>
  key :locale,     String

end
